version: "3.3"
services:
  kita-attendance:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: kita-attendance:dev
    container_name: kita-attendance
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.kita-attendance.entrypoints=websecure"
      - "traefik.http.routers.kita-attendance.rule=Host(`attendance.kitakeluarga.com`)"
      - "traefik.http.routers.kita-attendance.service=kita-attendance"
      - "traefik.http.services.kita-attendance.loadbalancer.server.port=80"

#      - "traefik.http.routers.kita-attendance.middlewares=corsHeader@file"

networks:
  proxy:
    external: true